### ISSUE TITLE
Resources should be tested

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#172]
We could set up some JSON validation checks for the game's resources.

**Comment by mafagafogigante** [comment]
@UnknownNPC committed some important file-existence checks for this with #289.

Next steps include checking for integers being in valid integer ranges and **required** values being present in all JSON objects of the file. I don't know if there is a thing such as a JSON testing framework, otherwise we will have to write some high level test specifications about what is required for each JSON file.

**Comment by UnknownNPC** [comment]
I will prepare validation requirements per json file and publish here for approvement. 
After that, we can discuss implementation.

**Comment by mafagafogigante** [comment]
Great, ask me if you have any questions.

**Comment by mafagafogigante** [comment]
This is what the test specification for the creatures.json file is going to look like (in pseudocode).

# creatures.json
    id: String (uppercase)
    type: String
    name:
        singular: String
        plural: Optional String
    tags: Array of String (uppercase)
    inventory: Array of String (uppercase)
    drops: Optional Array of Array of String and Double
    visibility: String (percentage)
    weight: Double
    health: Integer
    attack: Integer
    attackAlgorithmID: String (uppercase)

# Implementation notes

If something is an Optional T it may either **not be present** or be present and be a **T**.

Similarly to the way that we will have to use Percentage code to check whether or not a String is a valid percentage string, we might use ID-related code to check whether the ID strings are valid IDs.

**Comment by UnknownNPC** [comment]
I have checked current `json` files and existing `json factories` to achieve next results:
Pseudo code contains type, required/optional flag and basic validation description.

### wiki.json:
```
"articles": [
	"title": String (required),
	"content": String (required),
	"seeAlso": [
		: String (required)
	] (optional)
] (required)
```
### tutorial.json:
```
"tutorial": String (required)
```
	
### preface.json:
```
"format": String (required)
```

### poems.json:
```
"poems": [
	"title": String (required)
	"author": String (required)
	"content": String (required)
]
```
	
### locations.json:
```
locations : [
	"id": String (required; uppercase)
	"type": String (required; uppercase)
	"name": {
		"singular": String (required)
	} (required)
	"color": [
		: Int (required; range 0-255),
		: Int (required; range 0-255),
		: Int (required; range 0-255),
	] (required)
	"symbol": Char (required; uppercase)
	"info": String (required)
	"blobSize": Integer (required)
	"lightPermittivity": Double (required)
	"blockedEntrances": [
		: Char (required, uppercase)
	] (optional)
	"spawners": [
		"id": String (required, uppercase)
		"population": {
			"minimum": Integer (required)
			"maximum": Integer (required)
		} (required)
		"delay": Integer (required)
	] (optional)
	"items": [
		"id": String (uppercase)
		"probability": Double (required)
	] (optional)
] (required)
```

### items.json
```
"items": [
	"id": String (required; uppercase)
	"type": String (required)
	"name": {
		"singular": String (required)
		"plural": String (optional)
	}
	"tags": [
		: String (required; uppercase)
	] (required)
	"unique": Boolean (optional; default = false)
	"integrity": {
		"current": Integer (required)
		"maximum": Integer (required)
	} (required)
	"weight": Double (required)
	"visibility": String (percent type, eg. 60.00%; required)
	"luminosity": String (dungeon percent type, eg. 60.00%; optional)
	"decompositionPeriod": String (dungeon period type, eg. 1 month; optional)
	"damage": Integer (required)
	"hitRate": String (dungeon percent type, eg. 60.00%; required)
	"integrityDecrementOnHit": Integer (required)
	"nutrition": Integer (optional)
	"integrityDecrementOnEat": Integer (optional)
	"text": String (optional)
	"spell": String (optional; uppercase)
] (required)
```

### hints.json
```
"strings": [
	: String (optional)
] (required)
```

### dreams.json 
```
"strings": [
	: String (optional)
] (required)
```
	
### creatures.json
```
"creatures": [
	"id": String (required; uppercase)
	"type": String (required)
	"name": {
		"singular: String (required)
		"plural: String (optional)
	} (required)
	"tags": [
		: String (required, uppercase)
	] (optional)
	"inventoryItemLimit": Integer (required)
	"inventoryWeightLimit": Integer (required)
	"inventory": [
		: String (required)
	] (optional)
	"luminosity": String (dungeon percent type, eg. 60.00%; optional)
	"drops": [
		[
			: String (required, uppercase)
			: Double (required)
		]
	] (optional)
	"visibility": (dungeon percent type, eg. 60.00%; required)
	"weight": Double (requried)
	"health": Integer (required)
	"attack": Integer (required)
	"attackAlgorithmID": String (required)
	"weapon": String (uppercase; optional)
] (required)
```

### achievements.json
```
"achievements": [
	"id": String (required, uppercase)
	"name": String (required)
	"info": String (required)
	"text": String (required)
	"battleRequirements": [
		"query": {
			 "id": String (optional)
			 "type": String (optional)
			 "causeOfDeath": {
				"type": String (required; uppercase)
				"id": String (required; uppercase)
			 } (optional)
			 "partOfDay": String (optional)
		} (required)
		"count": Integer (required)
	] (optional)
	"explorationRequirements": [
		"killsByLocationID": {
			"String" : Integer (String should be locationID; required)
		} (optional)
		"maximumNumberOfVisits": {
			"String" : Integer (String should be locationID; required)
		}
		"visitedLocations": {
			"String" : Integer (String should be locationID; required)
		}
	] (optional)
] (required)
```

**Comment by UnknownNPC** [comment]
Also, I am planning to add ID dependencies a little bit late.

**Comment by UnknownNPC** [comment]
One question. 
Did you plan to use existing factories for `json` testing or should it be new code for src/test only? 
If we need something new, `json` property names should be replaced to the class with constants (eg. `explorationRequirements`, `killsByLocationID` names etc in `AchievementStoreFactory`).

**Comment by mafagafogigante** [comment]
Amazing work, you got some restrictions I didn't think about.

---

I planned on having a project-specific JSON testing framework.

So there would be one interface `JsonRules` with one method `validate(JsonObject)`. We would then use a factory to construct `JsonRules` implementations which we would then use to test the JSON resources.

    JsonRulesFactory.arrayOf(JsonRulesFactory.string())  // Defines an array of strings.

This object would be able to recursively evaluate whether or not `JsonObjects` we need to test are valid or not (see if the object is an array, if it is, see if each of its elements obey the restrictions imposed by the type of the array, and so on).

Some more examples of the concept:

    // { "count": [0..100] }
    JsonRulesFactory.object(JsonRulesFactory.pair("count", JsonRulesFactory.boundInteger(0, 100)))

As the member names do not need to match the class fields, this should be completely independent of what the class names are (otherwise refactoring a class could break tests which had no reason the break).

The names of the interfaces can be discussed, what matters more is how we are going to test each file.

**Comment by UnknownNPC** [comment]
Thank you for your response. 
The idea looks fine and clear, but it doesn't cover ID validation between `json` files (eg. achievements.explorationRequirements[n].killsByLocationID should check locations[n].id to make sure that location ID exists). 
In addition, I have found interesting project based on `scala parser combinator` for json DSL validation ([this](https://github.com/nparry/orderly4jvm)). Looks like the project is no longer supported, but it hints at ideas about validation using own diagrammatic rules or json scheme. What do you think about it?

**Comment by mafagafogigante** [comment]
That's an interesting finding.

I've googled a bit more and found [1](https://github.com/fge/json-schema-validator), [2](https://github.com/everit-org/json-schema), and [3](https://github.com/networknt/json-schema-validator) as Java-based JSONSchema validators. They all have their issues, but most of all JSONSchema seems unnecessarily hard to extend. Although I will support code reuse when possible, I don't think it is the best idea here.

---

I like what you are thinking about cross-validation, but it depends on what we are going to test. If they were some sort of resource unit tests, we should only check for the formats and assume everything else works (this way locations.json cannot possibly break achievements.json). However, I think some cross validation is a good idea.

See that we could have a private implementation of JsonType called LocationIdJsonType which performed both the Id checks but also kept a static index of all location ids we have and looked up if the Id we are trying to validade is actually a location Id. This shouldn't even be too much harder than the rest to get working.

Note, however, that this may be done as an iteration further down the road, going from no tests at all to partial schema tests is already a very good improvement.

**Comment by UnknownNPC** [comment]
I suppose, the task is clear right now. I will start with implementation.
Thank you.

**Comment by mafagafogigante** [comment]
This may need several redesigns before merging, I will help with code when needed and perform the required refactorings.

Ideally there should be three new things:

+ The framework itself (in src/main/java/org/mafagafogigante/dungeon/schema/)
+ The framework tests (in the corresponding src/test/... path)
+ The tests for our JSON (we will se where these go)

It may not be evident, but the first thing that must be tested is the testing code itself, so we are sure it works as it needs to before we allow it to judge our JSON assets.

It's good practice to make these efforts as unfinished pull requests (whenever you have a few Json validators working with their tests, open a PR for them). This allow us to discuss design early on and reduce the amount of work that will need to be redone.

Good luck and feel free to hit me up if you need anything.

**Comment by mafagafogigante** [comment]
With huge help from @UnknownNPC now we have some assets with which we can test the actual JSON resources bundled with the game.

The implementation of foreign tests (lookup on other resource files) and (maybe) JSON test hints (if all objects have a certain optional property, suggest that it may not be optional) can be delayed for another issue, later on.
