### ISSUE TITLE
Migrating to Java 7

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#183]
I've decided to migrate to Java 7 as this will solve a bunch of issues and won't cause major problems to anyone. Even Java 7 has already reached public EOL.

This would facilitate #156
This would solve #180 
This would solve #182

**Comment by badgersow** [comment]
Hi!
Thanks for the project, I enjoyed the source code a lot.

Is there a migration ticket to Java 9? 
It would help a lot with future development and contributions.

**Comment by mafagafogigante** [comment]
You can see that when I moved from Java 6 to Java 7 it was already pretty late according to Oracle. The next "migration" will probably be to Java 8 and only then to Java 9.

The only reason the project has stayed in Java 7 is that I don't see a reason for Java 8 (or 9) in this project.

> It would help a lot with future development and contributions.

I don't know about that. I don't think that not having the newest language features is the biggest contribution barrier here.
