### ISSUE TITLE
Should test for unused items and creatures

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#268]
It would be useful to have tests that ensured that each item and creature were mentioned by at least one location in the `locations.json` configuration file with a positive probability.

**Comment by mafagafogigante** [comment]
@UnknownNPC this is related to #172.

After we are done with the JSON testing framework, we must remember to have this testing done.

**Comment by mafagafogigante** [comment]
@UnknownNPC what do you think about this issue?

It would be ideal if we could ensure that the isolated tests regarding JSON values run before cross-file tests are fired, does JUnit support this?

We should then ensure that all items declared are used in the creatures or locations files and all creatures are used in the locations.

**Comment by UnknownNPC** [comment]
@mafagafogigante, we can group tests in suites for order control, [junit doc here](http://junit.sourceforge.net/javadoc/org/junit/runners/Suite.html).
if you do not mind, I copy your message from `gitter` as quote:
>So in CreatureJsonTest (I don't remember the actual name) we should have a method that makes a set of ids seen in the locations.json file and if we find a creature id that is not used there, we fail the test.

Sounds fine. I will share draft code when get some useful results.

**Comment by mafagafogigante** [comment]
I read about JUnit suites, but I don't think they will be a good solution as they seem to clutter the tests a lot.

I do think that what we agreed upon yesterday is a sensible solution, and it doesn't rely on ordering.

We should have a `SpecificIdJsonRule` that is instantiated from a set of Ids. Then we check whether or not the fields have one of these specific ids instead of any id, and if any of the ids haven't been used at least once, we throw an exception.

So in the beginning of the location tests, we create a `SpecificIdJsonRule` for item ids from the items JSON file.

**Comment by mafagafogigante** [comment]
Closed.
