### ISSUE TITLE
Should have JSON Enum rule

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#357]
The only valid tag values are those in an enumerated type. It would be best to have a JSON rule that got an enum class and only validated strings which map to a valid value of that enum.

- [x] Devise this JsonRule.
- [x] Write tests for it.
- [x] Use it to test item rarity strings.
- [x] Update items and locations tests to use this rule.

**Comment by UnknownNPC** [comment]
Could you please assign it to me?

**Comment by mafagafogigante** [comment]
Yes, will do.

**Comment by mafagafogigante** [comment]
I think you need to follow a link in an email GitHub will send you about this repository before I can assign things to you.

**Comment by UnknownNPC** [comment]
@mafagafogigante, thank you for invitation. I have already assigned it to myself.

**Comment by mafagafogigante** [comment]
Yeah, you should be able to. I don't have a lot of control over what permissions you have, just don't merge your own PRs before I review them and we should be OK.
