### ISSUE TITLE
Feedback command

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#72]
Discuss: a feedback command that allows the player to send feedback (**to whom?**) in the game.

A first simple version could send an e-mail to me (mafagafogigante@gmail.com) but that does not look right. Having a server that could get these messages and update a static page with them would be neat.

**Comment by mafagafogigante** [comment]
@narcolytic what are your thoughts on Twitter integration? So the player could log in and tweet feedback. Possibly with a SS, I suppose.

**Comment by mafagafogigante** [comment]
@neurolytic what are your thoughts on Twitter integration? So the player could log in and tweet feedback. Possibly with a SS, I suppose.

**Comment by neurolytic** [comment]
As someone who doesn't use Twitter, I'm not sure. Tweets go out to everyone who follows you, right? You can't 'send a tweet' to someone? So anyone who sends feedback to us would be broadcasting that to everyone they know/the public? That could actually be a clever way of spreading awareness of the game, but would rely on the screenshots being fairly compelling--which honestly is probably hard to do with a text adventure, though I'm sure it's possible.

**Comment by mafagafogigante** [comment]
I agree on the SS part. It'd be a tweet that mentioned us (maybe the game itself gets a profile that I get to manage or I just use mine) so that we would be notified whenever someone sent any kind of feedback.

This could also open doors to trolling and vandalism, which sure would be a problem.

**Comment by mafagafogigante** [comment]
Closed as this is not worth the hassle. At least not for now.
