### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#79]
A tag system for item properties. Instead of maintaining food = true, weapon = true and the like, the game will keep a list of tags such as FOOD, SHARP, WEAPON etc.

**Comment by neurolytic** [comment]
This could be one other way to keep things like the getWeight() branching clean: a tag like WEIGHT_VARIES_WITH_INTEGRITY that could also apply to things like ammunition for arrows/slings.

**Comment by mafagafogigante** [comment]
Exactly. Good point.
Reading item 50 of Effective Java I thought that instead of using Strings for tags, maybe the game should have a Tag enumerated type.

**Comment by neurolytic** [comment]
I would definitely think that's better. Are you thinking just a list of tags on the item that get a compare run through every time we're checking an item for a tag? Or maybe a map? The first sounds like a lot of checks but then I doubt any one item would have SO many tags.

**Comment by mafagafogigante** [comment]
This <http://docs.oracle.com/javase/7/docs/api/java/util/HashSet.html>.

On Fri, May 1, 2015 at 9:26 PM, Alexander <notifications@github.com> wrote:

> I would definitely think that's better. Are you thinking just a list of
> tags on the item that get a compare run through every time we're checking
> an item for a tag? Or maybe a map? The first sounds like a lot of checks
> but then I doubt any one item would have SO many tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mafagafogigante/dungeon/issues/79#issuecomment-98268029>
> .
>



-- 
Bernardo Sulzbach

**Comment by mafagafogigante** [comment]
Are you a CS student?

**Comment by neurolytic** [comment]
No hurt taken, I am not a cs student.
