### ISSUE TITLE
Creature tags

### ISSUE THREAD

**Issue by neurolytic** [mafagafogigante/dungeon#86]
Implementing creature tags like UNDEAD can help make the attack algorithm code more generic and modular, while tags like NO_CORPSE would be fairly mandatory for ghosts/wisps/other magical type enemies, or something like NO_MEAT or TOXIC_MEAT... are probably self explanatory.

**Comment by mafagafogigante** [comment]
Agreed. This gave me an idea.

**Comment by mafagafogigante** [comment]
@neurolytic Here. Would you be up for doing this now? I was working on corpses and saw the need for creature tags. I think that just ``CORPSE`` is OK for now.

**Comment by neurolytic** [comment]
A creature tag called CORPSE? Like, to define creatures that have corpses?

**Comment by mafagafogigante** [comment]
Yeah. Implement tags for creatures. For now, corpse should suffice.

**Comment by mafagafogigante** [comment]
What do you think about not making a creature an Item after it dies? Resurrection, butchering and a lot of other stuff would be easier that way. The resources could specify a time until a creature disappears.

**Comment by neurolytic** [comment]
I can conceive of situations in which you'd want corpses to be items, and personally I think the allure of these sorts of open-world games is flexibility. The less freedom you have to do things (even weird things that don't necessarily have any point, like being able to toss a corpse into a lake or something), the less open it feels. Just my figuring. Depends on what feel you're going for exactly.

**Comment by mafagafogigante** [comment]
I agree with you.

**Comment by neurolytic** [comment]
I remember this old game I played as a kid, Doom-level graphics but it was a dungeon crawler. There was this table you could take any dead monster to and it would resurrect them so you could fight them again. For some reason I did this over and over, it was just neat to have some weird little side thing you could do with the things in the game world.

**Comment by mafagafogigante** [comment]
After we get trees, tables and chests going the number of possibilities will increase dramatically. It is really important that you bring these ideas to the table so that we can discuss what to implement / work on next. Mind going to HipChat?

**Comment by mafagafogigante** [comment]
Done. The tags are there.

I would like to point out that I think it is better to use tags for things that exist. As if they were ``true`` flags (even if this increase the amount of tags we need).
For instance, having ``CORPSE`` for 95% of the creatures instead of ``NO_CORPSE`` for only 5%.

Next goal: #94
