### ISSUE TITLE
Additional item tags

### ISSUE THREAD

**Issue by ghost** [mafagafogigante/dungeon#87]
I wanted a place to collect ideas for additional item tags that may likely become necessary but aren't quite yet. I hate keeping ideas in my head, better to get them out. First up:

NO_DROP - Item cannot be dropped and does not drop on death (goes into limbo with the creature reference). For 'NPC only' items that the player should never see, and possibly for quest items or maybe cursed items.

**Comment by mafagafogigante** [comment]
Find an expression about how an item reacts with water. Weather will moist some items up, swords may be corroded for the sake of reality. Wet sticks do less damage, etc.
