### ISSUE TITLE
Food weight not varying as it should

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#88]
Looks like you didn't do your homework, @neurolytic 
![bug](https://cloud.githubusercontent.com/assets/8271090/7466005/fc432dda-f2b1-11e4-9559-2d61d38c4eb8.PNG)
You missed adding the WEIGHT_VARIES_... to the foods!
P.S.: I am not angry.

**Comment by mafagafogigante** [comment]
Try branching now and submitting a PR not from your master branch.

**Comment by neurolytic** [comment]
Whoops! That was goofy.
