### ISSUE TITLE
Could Creature.health and Item.integrity be unified in Entity?

### ISSUE THREAD

**Issue by ghost** [mafagafogigante/dungeon#91]
After promoting Weight to an Entity field, it sort of put me in the mind of other such unifications. It might be cool to do it this way because it would enable, say, area attack spells that damage both enemies and their items. For example, a Fireball explosion damaging a wooden shield.

**Comment by mafagafogigante** [comment]
Currently, combat is 1x1. So this is not OK for me. Also, I am about to commit something big. It could be a problem to merge later. =(

Go to the HipChat channel.

**Comment by neurolytic** [comment]
Well, I mean, the area attack part isn't important. Any direct fire spell against an enemy should/could theoretically damage his items.

**Comment by mafagafogigante** [comment]
Agreed. But this would require yet another mechanism. I think it is fine the way it is now. Maybe we change it later on, OK?

**Comment by neurolytic** [comment]
Oh yes, I just wanted a place to put the thought. It's not exactly urgent.
